services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=file:/data/prod.db
    volumes:
      - logimeet-data:/data
    restart: unless-stopped

volumes:
  logimeet-data:
